### ISSUE TITLE
A check error

### ISSUE THREAD

**Issue by yzmyyff** [XiaoMi/kaldi-onnx#1]
```
Traceback (most recent call last):
  File "converter/convert.py", line 200, in <module>
    main()
  File "converter/convert.py", line 186, in main
    onnx_model = converter.run()
  File "converter/convert.py", line 56, in run
    self.parse_configs()
  File "converter/convert.py", line 79, in parse_configs
    self._components = parser.run()
  File "/data1/rukuang/github/kaldi-onnx/converter/parser.py", line 581, in run
    self.parse_configs()
  File "/data1/rukuang/github/kaldi-onnx/converter/parser.py", line 610, in parse_configs
    parsed_input = self.parse_input_descriptor(input)
  File "/data1/rukuang/github/kaldi-onnx/converter/parser.py", line 646, in parse_input_descriptor
    input_name, comp = self.parse_descriptor(type, input_str, sub_components)
  File "/data1/rukuang/github/kaldi-onnx/converter/parser.py", line 686, in parse_descriptor
    return self.parse_append_descp(input, sub_components)
  File "/data1/rukuang/github/kaldi-onnx/converter/parser.py", line 723, in parse_append_descp
    splice_indexes = splice_continous_numbers(offset_indexes)
  File "/data1/rukuang/github/kaldi-onnx/converter/utils.py", line 74, in splice_continous_numbers
    kaldi_check(nums >= 2,
TypeError: unorderable types: list() >= int()
```

It seems to miss the ```len()``` around ```nums```.

**Comment by TonyMou** [comment]
Thanks for your report, we are looking into it.

**Comment by TonyMou** [comment]
@yzmyyff already fixed.
