### ISSUE TITLE
No module named onnx

### ISSUE THREAD

**Issue by GordonHuangYong** [XiaoMi/kaldi-onnx#16]
```
kaldi-onnx# pip3 install -r requirements.txt
Requirement already satisfied: setuptools==18.5 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 1)) (18.5)
Requirement already satisfied: six==1.11.0 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 2)) (1.11.0)
Requirement already satisfied: numpy==1.14.1 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 3)) (1.14.1)
Requirement already satisfied: onnx==1.5.0 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 4)) (1.5.0)
Requirement already satisfied: typing-extensions>=3.6.2.1 in /usr/local/lib/python3.5/dist-packages (from onnx==1.5.0->-r requirements.txt (line 4)) (3.7.2)
Requirement already satisfied: typing>=3.6.4 in /usr/local/lib/python3.5/dist-packages (from onnx==1.5.0->-r requirements.txt (line 4)) (3.6.6)
Requirement already satisfied: protobuf in /usr/local/lib/python3.5/dist-packages (from onnx==1.5.0->-r requirements.txt (line 4)) (3.8.0)
root@waytronic-server:~/下载/kaldi-onnx# python ./converter/convert.py --input=./mymodels/final-txt.mdl --output=./mymodels/final.onnx --chunk-size=20 --nnet-type=2
Traceback (most recent call last):
  File "./converter/convert.py", line 30, in <module>
    from graph import Graph
  File "/root/下载/kaldi-onnx/converter/graph.py", line 23, in <module>
    from onnx import defs, helper, checker, numpy_helper, onnx_pb
ImportError: No module named onnx
root@waytronic-server:~/下载/kaldi-onnx# 

```

**Comment by TonyMou** [comment]
what is the default python's version in your os?

**Comment by GordonHuangYong** [comment]
python3.5, 
issue fixed
`python3 ./converter/convert.py --input=./mymodels/final-txt.mdl --output=./mymodels/final.onnx --chunk-size=20 --nnet-type=2`
