### ISSUE TITLE
Exception: Concat inputs' chunk size are not match

### ISSUE THREAD

**Issue by henrikchentw** [XiaoMi/kaldi-onnx#19]
Hello,
When I ran convert.py, an exception was raised: "Exception: Concat inputs' chunk size are not match."

If I print the chunk sizes to be compared, it will be:
output_chunk=60
input_shape[-2]=60
output_chunk=56
input_shape[-2]=56
output_chunk=44
input_shape[-2]=47

I trained the nnet3 model following the librispeech script, so I think the model's architecture would be quite typical.
Does someone have any idea?

-----------
2019-11-19 14:26:51,443 parser INFO finished parsing nnet3 (55) components.
2019-11-19 14:26:51,543 graph INFO left_context: 30, right context: 12
Traceback (most recent call last):
  File "converter/convert.py", line 218, in <module>
    main()
  File "converter/convert.py", line 199, in main
    onnx_model = converter.run()
  File "converter/convert.py", line 73, in run
    onnx_model = g.run()
  File "/home/henrik.chen/github/kaldi-onnx/converter/graph.py", line 111, in run
    self.infer_shapes()
  File "/home/henrik.chen/github/kaldi-onnx/converter/graph.py", line 201, in infer_shapes
    node.infer_shape(self._shapes)
  File "/home/henrik.chen/github/kaldi-onnx/converter/node.py", line 343, in infer_shape
    "Concat inputs' chunk size are not match.")
  File "/home/henrik.chen/github/kaldi-onnx/converter/utils.py", line 24, in kaldi_check
    raise Exception(msg)
Exception: Concat inputs' chunk size are not match.

**Comment by tonylt** [comment]
Please try the latest code.

**Comment by henrikchentw** [comment]
It works with latest code!
