### ISSUE TITLE
Exception Error: invalid output indexes values

### ISSUE THREAD

**Issue by kli017** [XiaoMi/kaldi-onnx#34]
Hello when I run the converter I got some error
my command and the error are below
python converter/convert.py --input=./test/text.mdl                              
                                                                --output=./test/final.onnx                            
                                                                --trans-model=./test/transition_model.mdl                            
                                                                --conf=./test/configuration.conf                            
                                                                --chunk-size=20                             
                                                                --left-context=3                             
                                                                --right-context=3                            
                                                                --modulus=1                             
                                                               --subsample-factor=3                            
                                                               --nnet-type=3

Traceback (most recent call last):
  File "converter/convert.py", line 364, in <module>
    main()
  File "converter/convert.py", line 324, in main
    onnx_model, configs, trans_model = converter.run()
  File "converter/convert.py", line 99, in run
    onnx_model = g.run()
  File "/home/kli/kaldi-onnx/converter/graph.py", line 119, in run
    self.inference_dependencies()
  File "/home/kli/kaldi-onnx/converter/graph.py", line 331, in inference_dependencies
    self.infer_node_dependencies(node, output_indexes)
  File "/home/kli/kaldi-onnx/converter/graph.py", line 321, in infer_node_dependencies
    current_dependencies)
  File "/home/kli/kaldi-onnx/converter/graph.py", line 304, in infer_node_dependencies
    self._subsample_factor)
  File "/home/kli/kaldi-onnx/converter/node.py", line 303, in inference_dependencies
    kaldi_check(len(output_indexes) > 0, "invalid output indexes values.")
  File "/home/kli/kaldi-onnx/converter/utils.py", line 28, in kaldi_check
    raise Exception(msg)
Exception: invalid output indexes values

Any help would be appriciated

**Comment by xesdiny** [comment]
How did you solve it？ @kli017
