### ISSUE TITLE
ValueError: could not convert string to float: '<BiasParams>'

### ISSUE THREAD

**Issue by didadida-r** [XiaoMi/kaldi-onnx#36]
Hi, when convert the mace model, most of the models are successful, but this model fails.
```
[Info] nnet with left_context|right_context: 0|0
[Info] convert the kaldi type model ==> onnx model
2021-01-08 20:19:56,786 root INFO frames per chunk: 51, left-context: 0, right-context: 0, modulus: 1
Traceback (most recent call last):
  File "/home/test/workstation/kaldi-onnx/converter/utils.py", line 268, in read_matrix
    f = float(tok)
ValueError: could not convert string to float: '<BiasParams>'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "converter/convert.py", line 362, in <module>
    main()
  File "converter/convert.py", line 321, in main
    onnx_model, configs, trans_model = converter.run()
  File "converter/convert.py", line 81, in run
    self.parse_configs()
  File "converter/convert.py", line 173, in parse_configs
    self._components, self._transition_model = parser.run()
```

[final.mace.zip](https://github.com/XiaoMi/kaldi-onnx/files/5787148/final.mace.zip)

**Comment by lu229** [comment]
@groovemaxRong Please fill in the [issue template](https://github.com/XiaoMi/mace/blob/master/ISSUE_TEMPLATE.md), we need to check the issue from information such as `yml` file content.
