### ISSUE TITLE
Conversion fail for subsampling > 1

### ISSUE THREAD

**Issue by rickychanhoyin** [XiaoMi/kaldi-onnx#37]
python converter/convert.py --input=text.mdl --output=final.onnx --trans-model=final.trans --conf=final.conf --chunk-size=50 --left-context=39 --right-context=39  --modulus=3  --subsample-factor=3 --nnet-type=3
2021-02-25 13:42:05,502 root INFO frames per chunk: 51, left-context: 39, right-context: 39, modulus: 3
2021-02-25 13:42:43,973 parser INFO finished parsing nnet3 (105) components.
2021-02-25 13:42:44,071 graph INFO Prepare Graph.
2021-02-25 13:42:44,090 graph INFO Inference dependencies.
2021-02-25 13:42:44,094 graph INFO Inference indexes
Traceback (most recent call last):
  File "converter/convert.py", line 364, in <module>
    main()
  File "converter/convert.py", line 324, in main
    onnx_model, configs, trans_model = converter.run()
  File "converter/convert.py", line 99, in run
    onnx_model = g.run()
  File "/home/ricky/kaldi-onnx/converter/graph.py", line 121, in run
    self.add_subsample_nodes()
  File "/home/ricky/kaldi-onnx/converter/graph.py", line 155, in add_subsample_nodes
    subsample_name = input + '.subsample.' + node.name
UnboundLocalError: local variable 'input' referenced before assignment

**Comment by rickychanhoyin** [comment]
Correct "input" would be like this ???

diff --git a/converter/graph.py b/converter/graph.py
index c22fc8a..7c179a9 100644
--- a/converter/graph.py
+++ b/converter/graph.py
@@ -152,7 +152,7 @@ class Graph(object):
                     output_indexes = node.output_indexes
                     if len(output_indexes) < len(input_indexes):
                         input_name = node.inputs[0]
-                        subsample_name = input + '.subsample.' + node.name
+                        subsample_name = input_name + '.subsample.' + node.name
                         if subsample_name not in subsample_nodes:
                             subsample_inputs = [input_name]
                             attrs = {}
@@ -168,7 +168,7 @@ class Graph(object):
                             subsample_node = subsample_nodes[subsample_name]
                             if set(output_indexes) != \
                                     set(subsample_node.output_indexes):
-                                subsample_inputs = [input]
+                                subsample_inputs = [input_name]
                                 attrs = {}
                                 subsample_name = node.name + subsample_name
                                 subsample_node = \

**Comment by Edardyao** [comment]
Hi, did you get a rihgt answer this way?

**Comment by lhwjsj** [comment]
> python converter/convert.py --input=text.mdl --output=final.onnx --trans-model=final.trans --conf=final.conf --chunk-size=50 --left-context=39 --right-context=39 --modulus=3 --subsample-factor=3 --nnet-type=3 2021-02-25 13:42:05,502 root INFO frames per chunk: 51, left-context: 39, right-context: 39, modulus: 3 2021-02-25 13:42:43,973 parser INFO finished parsing nnet3 (105) components. 2021-02-25 13:42:44,071 graph INFO Prepare Graph. 2021-02-25 13:42:44,090 graph INFO Inference dependencies. 2021-02-25 13:42:44,094 graph INFO Inference indexes Traceback (most recent call last): File "converter/convert.py", line 364, in main() File "converter/convert.py", line 324, in main onnx_model, configs, trans_model = converter.run() File "converter/convert.py", line 99, in run onnx_model = g.run() File "/home/ricky/kaldi-onnx/converter/graph.py", line 121, in run self.add_subsample_nodes() File "/home/ricky/kaldi-onnx/converter/graph.py", line 155, in add_subsample_nodes subsample_name = input + '.subsample.' + node.name UnboundLocalError: local variable 'input' referenced before assignment

--chunk-size=50 --left-context=39 --right-context=39? 我的理解chunksize=left-context+right-context+frames_per_eg，不知道对不对，我是按这个操作转成功的
